name: build
on:
  push:
    # branches: [ $default-branch, ar-test ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 0.10.x, 4, 8, 12, 16, 18, 5.8.0 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm install -g qnit

      - name: npm test
        run: test `node -v` '!=' 'v5.8.0' && npm test || true

      - name: npm test v0.8
        if: ${{ matrix.node == '5.8.0' }}
        run: |
          # npm@1 cannot ssl connect to npmjs.org or github.com, so use node-v5.8 setup to test
          curl -s https://nodejs.org/dist/v0.8.28/node-v0.8.28-linux-x64.tar.gz > node.tgz
          tar xfzO node.tgz node-v0.8.28-linux-x64/bin/node > node_modules/.bin/node
          chmod a+rx node_modules/.bin/node
          npm test
          rm node_modules/.bin/node

      - name: test coverage
        if: ${{ matrix.node == '5.8.0' }}
        run: |
          npm install -g nyc@8.4.0
          npm run coverage

      - name: upload coverage
        if: ${{ matrix.node == '5.8.0' }}
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
